In [14]:
import pandas as pd
import json
import datasets
import csv

In [6]:
json.__dict__

{'__name__': 'json',
 '__doc__': 'JSON (JavaScript Object Notation) <https://json.org> is a subset of\nJavaScript syntax (ECMA-262 3rd edition) used as a lightweight data\ninterchange format.\n\n:mod:`json` exposes an API familiar to users of the standard library\n:mod:`marshal` and :mod:`pickle` modules.  It is derived from a\nversion of the externally maintained simplejson library.\n\nEncoding basic Python object hierarchies::\n\n    >>> import json\n    >>> json.dumps([\'foo\', {\'bar\': (\'baz\', None, 1.0, 2)}])\n    \'["foo", {"bar": ["baz", null, 1.0, 2]}]\'\n    >>> print(json.dumps("\\"foo\\bar"))\n    "\\"foo\\bar"\n    >>> print(json.dumps(\'\\u1234\'))\n    "\\u1234"\n    >>> print(json.dumps(\'\\\\\'))\n    "\\\\"\n    >>> print(json.dumps({"c": 0, "b": 0, "a": 0}, sort_keys=True))\n    {"a": 0, "b": 0, "c": 0}\n    >>> from io import StringIO\n    >>> io = StringIO()\n    >>> json.dump([\'streaming API\'], io)\n    >>> io.getvalue()\n    \'["streaming API"]\'\n\nCompact encoding::\n\n    >>> import json\n    >>> mydict = {\'4\': 5, \'6\': 7}\n    >>> json.dumps([1,2,3,mydict], separators=(\',\', \':\'))\n    \'[1,2,3,{"4":5,"6":7}]\'\n\nPretty printing::\n\n    >>> import json\n    >>> print(json.dumps({\'4\': 5, \'6\': 7}, sort_keys=True, indent=4))\n    {\n        "4": 5,\n        "6": 7\n    }\n\nDecoding JSON::\n\n    >>> import json\n    >>> obj = [\'foo\', {\'bar\': [\'baz\', None, 1.0, 2]}]\n    >>> json.loads(\'["foo", {"bar":["baz", null, 1.0, 2]}]\') == obj\n    True\n    >>> json.loads(\'"\\\\"foo\\\\bar"\') == \'"foo\\x08ar\'\n    True\n    >>> from io import StringIO\n    >>> io = StringIO(\'["streaming API"]\')\n    >>> json.load(io)[0] == \'streaming API\'\n    True\n\nSpecializing JSON object decoding::\n\n    >>> import json\n    >>> def as_complex(dct):\n    ...     if \'__complex__\' in dct:\n    ...         return complex(dct[\'real\'], dct[\'imag\'])\n    ...     return dct\n    ...\n    >>> json.loads(\'{"__complex__": true, "real": 1, "imag": 2}\',\n    ...     object_hook=as_complex)\n    (1+2j)\n    >>> from decimal import Decimal\n    >>> json.loads(\'1.1\', parse_float=Decimal) == Decimal(\'1.1\')\n    True\n\nSpecializing JSON object encoding::\n\n    >>> import json\n    >>> def encode_complex(obj):\n    ...     if isinstance(obj, complex):\n    ...         return [obj.real, obj.imag]\n    ...     raise TypeError(f\'Object of type {obj.__class__.__name__} \'\n    ...                     f\'is not JSON serializable\')\n    ...\n    >>> json.dumps(2 + 1j, default=encode_complex)\n    \'[2.0, 1.0]\'\n    >>> json.JSONEncoder(default=encode_complex).encode(2 + 1j)\n    \'[2.0, 1.0]\'\n    >>> \'\'.join(json.JSONEncoder(default=encode_complex).iterencode(2 + 1j))\n    \'[2.0, 1.0]\'\n\n\nUsing json.tool from the shell to validate and pretty-print::\n\n    $ echo \'{"json":"obj"}\' | python -m json.tool\n    {\n        "json": "obj"\n    }\n    $ echo \'{ 1.2:3.4}\' | python -m json.tool\n    Expecting property name enclosed in double quotes: line 1 column 3 (char 2)\n',
 '__package__': 'json',
 '__loader__': <_frozen_importlib_external.SourceFileLoader at 0x28b9eaab9d0>,
 '__spec__': ModuleSpec(name='json', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000028B9EAAB9D0>, origin='c:\\Users\\eglha\\miniconda3\\envs\\hackathon\\Lib\\json\\__init__.py', submodule_search_locations=['c:\\Users\\eglha\\miniconda3\\envs\\hackathon\\Lib\\json']),
 '__path__': ['c:\\Users\\eglha\\miniconda3\\envs\\hackathon\\Lib\\json'],
 '__file__': 'c:\\Users\\eglha\\miniconda3\\envs\\hackathon\\Lib\\json\\__init__.py',
 '__cached__': 'c:\\Users\\eglha\\miniconda3\\envs\\hackathon\\Lib\\json\\__pycache__\\__init__.cpython-311.pyc',
 '__builtins__': {'__name__': 'builtins',
  '__doc__': "Built-in functions, types, exceptions, and other objects.\n\nThis module provides direct access to all 'built-in'\nidentifiers of Python; for example, builtins.len is\nthe full name for the built-in function len().\n\nThis module is not normally accessed explicitly by most\napplications, but can be useful in modules that provide\nobjects with the same name as a built-in value, but in\nwhich the built-in of that name is also needed.",
  '__package__': '',
  '__loader__': _frozen_importlib.BuiltinImporter,
  '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>, origin='built-in'),
  '__build_class__': <function __build_class__>,
  '__import__': <function __import__(name, globals=None, locals=None, fromlist=(), level=0)>,
  'abs': <function abs(x, /)>,
  'all': <function all(iterable, /)>,
  'any': <function any(iterable, /)>,
  'ascii': <function ascii(obj, /)>,
  'bin': <function bin(number, /)>,
  'breakpoint': <function breakpoint>,
  'callable': <function callable(obj, /)>,
  'chr': <function chr(i, /)>,
  'compile': <function compile(source, filename, mode, flags=0, dont_inherit=False, optimize=-1, *, _feature_version=-1)>,
  'delattr': <function delattr(obj, name, /)>,
  'dir': <function dir>,
  'divmod': <function divmod(x, y, /)>,
  'eval': <function eval(source, globals=None, locals=None, /)>,
  'exec': <function exec(source, globals=None, locals=None, /, *, closure=None)>,
  'format': <function format(value, format_spec='', /)>,
  'getattr': <function getattr>,
  'globals': <function globals()>,
  'hasattr': <function hasattr(obj, name, /)>,
  'hash': <function hash(obj, /)>,
  'hex': <function hex(number, /)>,
  'id': <function id(obj, /)>,
  'input': <bound method Kernel.raw_input of <ipykernel.ipkernel.IPythonKernel object at 0x0000028BA2E69ED0>>,
  'isinstance': <function isinstance(obj, class_or_tuple, /)>,
  'issubclass': <function issubclass(cls, class_or_tuple, /)>,
  'iter': <function iter>,
  'aiter': <function aiter(async_iterable, /)>,
  'len': <function len(obj, /)>,
  'locals': <function locals()>,
  'max': <function max>,
  'min': <function min>,
  'next': <function next>,
  'anext': <function anext>,
  'oct': <function oct(number, /)>,
  'ord': <function ord(c, /)>,
  'pow': <function pow(base, exp, mod=None)>,
  'print': <function print(*args, sep=' ', end='\n', file=None, flush=False)>,
  'repr': <function repr(obj, /)>,
  'round': <function round(number, ndigits=None)>,
  'setattr': <function setattr(obj, name, value, /)>,
  'sorted': <function sorted(iterable, /, *, key=None, reverse=False)>,
  'sum': <function sum(iterable, /, start=0)>,
  'vars': <function vars>,
  'None': None,
  'Ellipsis': Ellipsis,
  'NotImplemented': NotImplemented,
  'False': False,
  'True': True,
  'bool': bool,
  'memoryview': memoryview,
  'bytearray': bytearray,
  'bytes': bytes,
  'classmethod': classmethod,
  'complex': complex,
  'dict': dict,
  'enumerate': enumerate,
  'filter': filter,
  'float': float,
  'frozenset': frozenset,
  'property': property,
  'int': int,
  'list': list,
  'map': map,
  'object': object,
  'range': range,
  'reversed': reversed,
  'set': set,
  'slice': slice,
  'staticmethod': staticmethod,
  'str': str,
  'super': super,
  'tuple': tuple,
  'type': type,
  'zip': zip,
  '__debug__': True,
  'BaseException': BaseException,
  'BaseExceptionGroup': BaseExceptionGroup,
  'Exception': Exception,
  'GeneratorExit': GeneratorExit,
  'KeyboardInterrupt': KeyboardInterrupt,
  'SystemExit': SystemExit,
  'ArithmeticError': ArithmeticError,
  'AssertionError': AssertionError,
  'AttributeError': AttributeError,
  'BufferError': BufferError,
  'EOFError': EOFError,
  'ImportError': ImportError,
  'LookupError': LookupError,
  'MemoryError': MemoryError,
  'NameError': NameError,
  'OSError': OSError,
  'ReferenceError': ReferenceError,
  'RuntimeError': RuntimeError,
  'StopAsyncIteration': StopAsyncIteration,
  'StopIteration': StopIteration,
  'SyntaxError': SyntaxError,
  'SystemError': SystemError,
  'TypeError': TypeError,
  'ValueError': ValueError,
  'Warning': Warning,
  'FloatingPointError': FloatingPointError,
  'OverflowError': OverflowError,
  'ZeroDivisionError': ZeroDivisionError,
  'BytesWarning': BytesWarning,
  'DeprecationWarning': DeprecationWarning,
  'EncodingWarning': EncodingWarning,
  'FutureWarning': FutureWarning,
  'ImportWarning': ImportWarning,
  'PendingDeprecationWarning': PendingDeprecationWarning,
  'ResourceWarning': ResourceWarning,
  'RuntimeWarning': RuntimeWarning,
  'SyntaxWarning': SyntaxWarning,
  'UnicodeWarning': UnicodeWarning,
  'UserWarning': UserWarning,
  'BlockingIOError': BlockingIOError,
  'ChildProcessError': ChildProcessError,
  'ConnectionError': ConnectionError,
  'FileExistsError': FileExistsError,
  'FileNotFoundError': FileNotFoundError,
  'InterruptedError': InterruptedError,
  'IsADirectoryError': IsADirectoryError,
  'NotADirectoryError': NotADirectoryError,
  'PermissionError': PermissionError,
  'ProcessLookupError': ProcessLookupError,
  'TimeoutError': TimeoutError,
  'IndentationError': IndentationError,
  'IndexError': IndexError,
  'KeyError': KeyError,
  'ModuleNotFoundError': ModuleNotFoundError,
  'NotImplementedError': NotImplementedError,
  'RecursionError': RecursionError,
  'UnboundLocalError': UnboundLocalError,
  'UnicodeError': UnicodeError,
  'BrokenPipeError': BrokenPipeError,
  'ConnectionAbortedError': ConnectionAbortedError,
  'ConnectionRefusedError': ConnectionRefusedError,
  'ConnectionResetError': ConnectionResetError,
  'TabError': TabError,
  'UnicodeDecodeError': UnicodeDecodeError,
  'UnicodeEncodeError': UnicodeEncodeError,
  'UnicodeTranslateError': UnicodeTranslateError,
  'ExceptionGroup': ExceptionGroup,
  'EnvironmentError': OSError,
  'IOError': OSError,
  'WindowsError': OSError,
  'open': <function io.open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)>,
  'copyright': Copyright (c) 2001-2023 Python Software Foundation.
  All Rights Reserved.

  Copyright (c) 2000 BeOpen.com.
  All Rights Reserved.

  Copyright (c) 1995-2001 Corporation for National Research Initiatives.
  All Rights Reserved.

  Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
  All Rights Reserved.,
  'credits':     Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands
      for supporting Python development.  See www.python.org for more information.,
  'license': See https://www.python.org/psf/license/,
  'help': Type help() for interactive help, or help(object) for help about object.,
  'execfile': <function _pydev_bundle._pydev_execfile.execfile(file, glob=None, loc=None)>,
  'runfile': <function _pydev_bundle.pydev_umd.runfile(filename, args=None, wdir=None, namespace=None)>,
  '__IPYTHON__': True,
  'display': <function IPython.core.display_functions.display(*objs, include=None, exclude=None, metadata=None, transient=None, display_id=None, raw=False, clear=False, **kwargs)>,
  'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x0000028BA4348C50>>},
 '__version__': '2.0.9',
 '__all__': ['dump',
  'dumps',
  'load',
  'loads',
  'JSONDecoder',
  'JSONDecodeError',
  'JSONEncoder'],
 '__author__': 'Bob Ippolito <bob@redivi.com>',
 'scanner': <module 'json.scanner' from 'c:\\Users\\eglha\\miniconda3\\envs\\hackathon\\Lib\\json\\scanner.py'>,
 'decoder': <module 'json.decoder' from 'c:\\Users\\eglha\\miniconda3\\envs\\hackathon\\Lib\\json\\decoder.py'>,
 'JSONDecoder': json.decoder.JSONDecoder,
 'JSONDecodeError': json.decoder.JSONDecodeError,
 'encoder': <module 'json.encoder' from 'c:\\Users\\eglha\\miniconda3\\envs\\hackathon\\Lib\\json\\encoder.py'>,
 'JSONEncoder': json.encoder.JSONEncoder,
 'codecs': <module 'codecs' (frozen)>,
 '_default_encoder': <json.encoder.JSONEncoder at 0x28b9eab8150>,
 'dump': <function json.dump(obj, fp, *, skipkeys=False, ensure_ascii=True, check_circular=True, allow_nan=True, cls=None, indent=None, separators=None, default=None, sort_keys=False, **kw)>,
 'dumps': <function json.dumps(obj, *, skipkeys=False, ensure_ascii=True, check_circular=True, allow_nan=True, cls=None, indent=None, separators=None, default=None, sort_keys=False, **kw)>,
 '_default_decoder': <json.decoder.JSONDecoder at 0x28b9eab8090>,
 'detect_encoding': <function json.detect_encoding(b)>,
 'load': <function json.load(fp, *, cls=None, object_hook=None, parse_float=None, parse_int=None, parse_constant=None, object_pairs_hook=None, **kw)>,
 'loads': <function json.loads(s, *, cls=None, object_hook=None, parse_float=None, parse_int=None, parse_constant=None, object_pairs_hook=None, **kw)>}

In [ ]:
with open("feverdataset_train.jsonl", "r", encoding="utf-8") as f:
    records = [json.loads(line) for line in f]

AttributeError: 'str' object has no attribute 'read'

In [9]:

df = pd.read_json("feverdataset_train.jsonl", lines=True)
df.head()

,id,verifiable,label,claim,evidence
0,75397,VERIFIABLE,SUPPORTS,Nikolaj Coster-Waldau worked with the Fox Broa...,"[[[92206, 104971, Nikolaj_Coster-Waldau, 7], [..."
1,150448,VERIFIABLE,SUPPORTS,Roman Atwood is a content creator.,"[[[174271, 187498, Roman_Atwood, 1]], [[174271..."
2,214861,VERIFIABLE,SUPPORTS,"History of art includes architecture, dance, s...","[[[255136, 254645, History_of_art, 2]]]"
3,156709,VERIFIABLE,REFUTES,Adrienne Bailon is an accountant.,"[[[180804, 193183, Adrienne_Bailon, 0]]]"
4,83235,NOT VERIFIABLE,NOT ENOUGH INFO,System of a Down briefly disbanded in limbo.,"[[[100277, None, None, None]]]"

In [10]:
refutes=df[df["label"]=="REFUTES"]
refutes['claim'].head(20)

3                     Adrienne Bailon is an accountant.
14      Stranger Things is set in Bloomington, Indiana.
16    Puerto Rico is not an unincorporated territory...
26    Peggy Sue Got Married is a Egyptian film relea...
27    Andy Roddick lost 5 Master Series between 2002...
28    As the Vietnam War raged in 1969, Yoko Ono and...
40                             Grace Jones is a dancer.
42    Willie Nelson dropped out of college after thr...
46    Furia is adapted from a short story by Anna Po...
51                C. S. Forester's first name was Carl.
52                        Kong: Skull Island is a book.
53                   The Challenge was a scripted show.
62                      Red Headed Stranger is a movie.
70                  Chester Bennington is not a singer.
73                 David Beckham has zero middle names.
74    Indiana Jones has only been portrayed by Harri...
78       Shane Black and Chris Miller wrote Iron Man 3.
79      La La Anthony was conceived on June 25th, 1979.
84                            Filmfare is about cheese.
85    Buckingham Palace lacks brightly colored scagl...
Name: claim, dtype: str

In [11]:
len(refutes)

29775

In [12]:
refutes.to_csv("fever_refuted.csv")

In [ ]:
refute1="World War II did not have campaigns occurring in Asia"
refute2="Large numbers of civilians were not executed during the French Revolution."

In [15]:
_DESCRIPTION = """\
We present a human-and-model-in-the-loop process for dynamically generating datasets and training better performing and more robust hate detection models. We provide a new dataset of ~40,000 entries, generated and labelled by trained annotators over four rounds of dynamic data creation. It includes ~15,000 challenging perturbations and each hateful entry has fine-grained labels for the type and target of hate. Hateful entries make up 54% of the dataset, which is substantially higher than comparable datasets. We show that model performance is substantially improved using this approach. Models trained on later rounds of data collection perform better on test sets and are harder for annotators to trick. They also perform better on HATECHECK, a suite of functional tests for online hate detection. See https://arxiv.org/abs/2012.15761 for more details.
"""

_CITATION = """\
@inproceedings{vidgen2021learning,
  title={Learning from the Worst: Dynamically Generated Datasets to Improve Online Hate Detection},
  author={Vidgen, Bertie and Thrush, Tristan and Waseem, Zeerak and Kiela, Douwe},
  booktitle={Proceedings of the 59th Annual Meeting of the Association for Computational Linguistics and the 11th International Joint Conference on Natural Language Processing (Volume 1: Long Papers)},
  pages={1667--1682},
  year={2021}
}
"""

_DOWNLOAD_URL = "https://raw.githubusercontent.com/bvidgen/Dynamically-Generated-Hate-Speech-Dataset/main/Dynamically%20Generated%20Hate%20Dataset%20v{version}.csv"
_VERSIONS = ("0.2.3", "0.2.2")


class Dynahate(datasets.GeneratorBasedBuilder):
    """Learning from the worst hate speech classification dataset."""
    BUILDER_CONFIGS = [datasets.BuilderConfig(name=version, version=version) for version in _VERSIONS]
    DEFAULT_CONFIG_NAME = "0.2.3"
    def _info(self):
        return datasets.DatasetInfo(
            description=_DESCRIPTION,
            features=datasets.Features(
                {
                    "acl.id": datasets.Value("string"),
                    "label": datasets.features.ClassLabel(names=["nothate", "hate"]),
                    "text": datasets.Value("string"),
                    "X1": datasets.Value("int32"),
                    "type": datasets.Value("string"),
                    "target": datasets.Value("string"),
                    "level": datasets.Value("string"),
                    "split": datasets.Value("string"),
                    "round.base": datasets.Value("int32"),
                    "annotator": datasets.Value("string"),
                    "round": datasets.Value("string"),
                    "acl.id.matched": datasets.Value("string")
                }
            ),
            homepage="https://arxiv.org/abs/2012.15761",
            citation=_CITATION,
        )

    def _split_generators(self, dl_manager):
        csv_path = dl_manager.download_and_extract(_DOWNLOAD_URL.format(version=self.config.name))
        return [
            datasets.SplitGenerator(name=datasets.Split.TRAIN, gen_kwargs={"csv_path": csv_path, "split": "train"}),
            datasets.SplitGenerator(name=datasets.Split.VALIDATION, gen_kwargs={"csv_path": csv_path, "split": "dev"}),
            datasets.SplitGenerator(name=datasets.Split.TEST, gen_kwargs={"csv_path": csv_path, "split": "test"}),
        ]

    def _generate_examples(self, csv_path, split):
        """Generate AG News examples."""
        with open(csv_path, encoding="utf-8") as csv_file:
            csv_reader = csv.reader(csv_file, delimiter=",")
            for id_, row in enumerate(csv_reader):
                if id_ == 0:
                    keys = row[:]
                else:
                    res = dict([(k, v) for k, v in zip(keys, row) if k != ""])
                
                    for k in ["X1", "round.base"]:
                        res[k] = int(res[k])
                    yield id_ - 1, res

In [1]:

# Option 2: pandas directly (simpler)
import pandas as pd
url = "https://raw.githubusercontent.com/bvidgen/Dynamically-Generated-Hate-Speech-Dataset/main/Dynamically%20Generated%20Hate%20Dataset%20v0.2.3.csv"
df = pd.read_csv(url)
print(df.head())
print(df.columns)

   Unnamed: 0    acl.id  X1  \
0           1      acl1   1
1           2     acl10   2
2           3    acl100   3
3           4   acl1000   4
4           5  acl10000   5

                                                text label      type  \
0                                dalits are lowlives  hate  notgiven
1             gay people are a burden to our society  hate  notgiven
2                              Arabs are not welcome  hate  notgiven
3  I'm not saying we should actually eliminate he...  hate  notgiven
4                       bananas are for black people  hate  notgiven

     target     level  split  round.base   annotator round acl.id.matched
0  notgiven  original  train           1  GNZuCtwed3     1            NaN
1  notgiven  original  train           1  GNZuCtwed3     1            NaN
2  notgiven  original  train           1  vDe7GN0NrL     1            NaN
3  notgiven  original  train           1  oemYWm1Tjg     1            NaN
4  notgiven  original   test           1  QiOKkCi7F8     1            NaN
Index(['Unnamed: 0', 'acl.id', 'X1', 'text', 'label', 'type', 'target',
       'level', 'split', 'round.base', 'annotator', 'round', 'acl.id.matched'],
      dtype='str')

In [4]:
hate=df[df['label']=='hate']
hate['text'].sample(20)

31917              She's got a black baby, it's disgusting
35505    I just saw this queer in town and he tried to ...
15224    For the last two months, we've been following ...
31675    This is exactly what the feminists are shoutin...
37826                 queers shouldn't be allowed to adopt
40174        I hope we get rid of all black people by 2030
15021                                    women are a virus
37143    if you are a man and you like men, you are not...
13660    U ain't white. Accept whatever injun or whatev...
18884    lets ask this question why Trump suck evil jew...
8400     I though paedo was spelt like poof and now I k...
30227    There were Jews who worked in the slave trade,...
30605    Frank Karmey was an astronomer who was fired f...
39852    I disagree with the rights of black people in ...
35715                                all gays are perverts
7951     WATever fucking noisy black chicks down my str...
2641     If we were to kill all the black women the wor...
13474    Women say: "Ewww! Women aren't objects. I'm a ...
27542    When I see these neo Nazi groups I feel better...
22131    Purchasing woman parts from a hospital and cal...
Name: text, dtype: str

In [13]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Download latest version
path = kagglehub.dataset_download("emineyetm/fake-news-detection-datasets")

print("Path to dataset files:", path)

Downloading to C:\Users\eglha\.cache\kagglehub\datasets\emineyetm\fake-news-detection-datasets\1.archive...

100%|██████████| 41.0M/41.0M [00:02<00:00, 16.9MB/s]

Extracting files...

Path to dataset files: C:\Users\eglha\.cache\kagglehub\datasets\emineyetm\fake-news-detection-datasets\versions\1

In [14]:
fake_news_pth=r"C:\Users\eglha\OneDrive\Documents\lesson_plan_LLM\data\News _dataset\Fake.csv"
fake_news=pd.read_csv(fake_news_pth)
fake_news.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [25]:
fake_news['war'].sample(20)

KeyError: 'war'

In [26]:
def search_term(search_term):
        term = str(search_term).lower()
        for text in fake_news['text'].astype(str):
            if term in text.lower():
                return text
        return "Not found"

print(search_term("war"))

On Friday, it was revealed that former Milwaukee Sheriff David Clarke, who was being considered for Homeland Security Secretary in Donald Trump s administration, has an email scandal of his own.In January, there was a brief run-in on a plane between Clarke and fellow passenger Dan Black, who he later had detained by the police for no reason whatsoever, except that maybe his feelings were hurt. Clarke messaged the police to stop Black after he deplaned, and now, a search warrant has been executed by the FBI to see the exchanges.Clarke is calling it fake news even though copies of the search warrant are on the Internet. I am UNINTIMIDATED by lib media attempts to smear and discredit me with their FAKE NEWS reports designed to silence me,  the former sheriff tweeted.  I will continue to poke them in the eye with a sharp stick and bitch slap these scum bags til they get it. I have been attacked by better people than them #MAGA I am UNINTIMIDATED by lib media attempts to smear and discredit me with their FAKE NEWS reports designed to silence me. I will continue to poke them in the eye with a sharp stick and bitch slap these scum bags til they get it. I have been attacked by better people than them #MAGA pic.twitter.com/XtZW5PdU2b  David A. Clarke, Jr. (@SheriffClarke) December 30, 2017He didn t stop there.BREAKING NEWS! When LYING LIB MEDIA makes up FAKE NEWS to smear me, the ANTIDOTE is go right at them. Punch them in the nose & MAKE THEM TASTE THEIR OWN BLOOD. Nothing gets a bully like LYING LIB MEDIA S attention better than to give them a taste of their own blood #neverbackdown pic.twitter.com/T2NY2psHCR  David A. Clarke, Jr. (@SheriffClarke) December 30, 2017The internet called him out.This is your local newspaper and that search warrant isn t fake, and just because the chose not to file charges at the time doesn t mean they won t! Especially if you continue to lie. Months after decision not to charge Clarke, email search warrant filed https://t.co/zcbyc4Wp5b  KeithLeBlanc (@KeithLeBlanc63) December 30, 2017I just hope the rest of the Village People aren t implicated.  Kirk Ketchum (@kirkketchum) December 30, 2017Slaw, baked potatoes, or French fries? pic.twitter.com/fWfXsZupxy  ALT- Immigration   (@ALT_uscis) December 30, 2017pic.twitter.com/ymsOBLjfxU  Pendulum Swinger (@PendulumSwngr) December 30, 2017you called your police friends to stand up for you when someone made fun of your hat  Chris Jackson (@ChrisCJackson) December 30, 2017Is it me, with this masterful pshop of your hat, which I seem to never tire of. I think it s the steely resolve in your one visible eye pic.twitter.com/dWr5k8ZEZV  Chris Mohney (@chrismohney) December 30, 2017Are you indicating with your fingers how many people died in your jail? I think you re a few fingers short, dipshit  Ike Barinholtz (@ikebarinholtz) December 30, 2017ROFL. Internet tough guy with fake flair. pic.twitter.com/ulCFddhkdy  KellMeCrazy (@Kel_MoonFace) December 30, 2017You re so edgy, buddy.  Mrs. SMH (@MRSSMH2) December 30, 2017Is his break over at Applebees?  Aaron (@feltrrr2) December 30, 2017Are you trying to earn your  still relevant  badge?  CircusRebel (@CircusDrew) December 30, 2017make sure to hydrate, drink lots of water. It s rumored that prisoners can be denied water by prison officials.  Robert Klinc (@RobertKlinc1) December 30, 2017Terrill Thomas, the 38-year-old black man who died of thirst in Clarke s Milwaukee County Jail cell this April, was a victim of homicide. We just thought we should point that out. It can t be repeated enough.Photo by Spencer Platt/Getty Images.

In [32]:
def search_term(search_term):
    term = str(search_term).lower()
    results = []
    for text in fake_news['text'].astype(str):
        if term in text.lower():
            results.append(text)
    print(f"Total Items containing the search term:{search_term} are: {len(results)}")
    return "\n".join(results) if results else "Not found"

print(search_term("sandy hook"))

Total Items containing the search term:sandy hook are: 76
It almost seems like Donald Trump is trolling America at this point. In the beginning, when he tried to gaslight the country by insisting that the crowd at his inauguration was the biggest ever   or that it was even close to the last couple of inaugurations   we all kind of scratched our heads and wondered what kind of bullshit he was playing at. Then when he started appointing people to positions they had no business being in, we started to worry that this was going to go much worse than we had expected.After 11 months of Donald Trump pulling the rhetorical equivalent of whipping his dick out and slapping it on every table he gets near, I think it s time we address what s happening: Dude is a straight-up troll. He gets pleasure out of making other people uncomfortable or even seeing them in distress. He actively thinks up ways to piss off people he doesn t like.Let s set aside just for a moment the fact that that s the least presidential  behavior anyone s ever heard of   it s dangerous.His latest stunt is one of the grossest yet.Everyone is, by now, used to Trump not talking about things he doesn t want to talk about, and making a huge deal out of things that not many people care about. So it wasn t a huge surprise when the president didn t discuss the Sandy Hook shooting of 2012 on the fifth anniversary of that tragic event. What was a huge surprise was that he not only consciously decided not to invite the victims  families to the White House Christmas party this year   as they have been invited every year since the massacre took place, along with others who share those concerns.In each of the past 4 years, President Obama invited gun violence prevention activists, gun violence survivors (including the Sandy Hook families) and supportive lawmakers to his Christmas party. Zero gun lobbyists were in attendance. pic.twitter.com/QePW9FtbSh  Shannon Watts (@shannonrwatts) December 15, 2017The last sentence of that tweet is important, because that s exactly who Donald Trump did invite to the White House Christmas party. Instead of victims. On the anniversary day.Yesterday was the 5 year mark of the mass shooting at Sandy Hook School, which went unacknowledged by the President. On the same day, he hosted a White House Christmas party to which he invited @NRA CEO Wayne LaPierre. Here he is at the party with @DanPatrick. pic.twitter.com/mUbKCIWGxB  Shannon Watts (@shannonrwatts) December 15, 2017Wayne LaPierre is the man who, in response to the Sandy Hook massacre, finally issued a statement that blamed gun violence on music, movies, and video games, and culminated with perhaps the greatest bit of irony any man has ever unintentionally conceived of: Isn t fantasizing about killing people as a way to get your kicks really the filthiest form of pornography? Yes. Yes, it is, Wayne.Anyway, Happy Holidays Merry Christmas from Donald Trump, everyone!Featured image via Alex Wong/Getty Images
 I like your Christ, I do not like your Christians. Your Christians are so unlike your Christ. That s a pretty easy quote from Gandhi to understand. The man was complicated and problematic in a lot of ways, but this one quote never loses its edge for me, because it s so simple.I have no doubt, however, that firebrand GOP Senate hopeful Roy Moore would dismiss it as the ramblings of a skinny brown cultist. I mean, Hinduism has to be a cult, since there s no story of a savior coming back from the dead, no fire and brimstone and angry gods. I mean, there are, but not Roy s angry God.Roy s angry God is apparently the guy responsible for the murders of 20 children and six teachers at Sandy Hook Elementary five years ago this December. You see, Roy s God is the one from the Old Testament of the Bible, and the book that Roy gets this particular idea from was apparently written 800 years before Christ came around. Laws were different then. You couldn t eat shrimp or cut your hair at the temples, and I guess if you were a biblical lady, you probably should have been essentially in hiding the entire time you menstruated, because holy shit, was that frowned on.In fact, that book of the Bible, Hosea, has 197 verses in it, and they re essentially all about how terrible everyone is, and how God wants to smite them because they don t love Him enough.They turned away from the Laws Of God, you see, and that meant the Almighty laid the smack down on them. Translated into current context, Roy Moore says, that means God instructed Adam Lanza to pull the trigger on those children and eventually himself, because America, like the Northern Kingdom of Israel before her, is worshiping false idols.Personally, I think Hosea himself was just an angry dude. His wife (Gomer) cheated on him, and God made him give his kids funny names, and he wasn t even sure if the last kid was his  Well, the story s pretty convoluted, really, but suffice it to say, if I had been designated as one of God s main spokesmen and I was going through some shit like Hosea was, I can imagine telling my wife that all the bad things happening to her were happening because she was a sinner.It s not very Christian, though.In fact, it s pretty gross. Here s video of the guy who s probably going to win a Senate seat in Alabama telling a church in the town of Guin that God murders children when He s angry:On TV today we played footage I found of Roy Moore saying the Newtown, CT. shooting happened because we forgot God's law. pic.twitter.com/jzyVD4tIcW  ?andrew kaczynski (@KFILE) September 27, 2017I know the Bible is a long book, but let s hope Roy gets to the New Testament soon.Featured image via Scott Olson/Getty Images
Donald Trump stuck his foot in his mouth again and pissed off our closest ally.A recent report indicates that the crime rate is rising in the United Kingdom due to gang-related activities and hate crimes against Muslims.Of course, rather than read the report to understand it, Trump took to Twitter to bellow about how  radical Islamic terror  is the cause and seemed to promote his Muslim ban as the way to  keep America safe! Just out report:  United Kingdom crime rises 13% annually amid spread of Radical Islamic terror.  Not good, we must keep America safe!  Donald J. Trump (@realDonaldTrump) October 20, 2017Trump s ridiculously uninformed commentary on the crime rate in the United Kingdom did not go over very well with British lawmakers, who promptly humiliated Trump with facts.Labour Party MP Chris Bryant told Trump to back off and reminded him that America has a massive gun violence problem. Butt out of it mister president,  Bryant said.  You have more murders in New York or Chicago every year than we do in the whole country so we re not going to take any lessons from you. Labour Party MP Stephen Doughty chimed in by telling the Daily Mail that Trump is  talking nonsense  and also took aim at Trump for not doing anything to stop mass shootings in America. Donald Trump would be better placed looking at issues in his own country such as the huge number of deaths from gun violence which despite repeated atrocities from Sandy Hook to Las Vegas, the US government have failed to take action on,  Doughty said.Liberal Democrat MP Jo Swinson slammed Trump as well, and went so far as to blame Trump s xenophobia for the rise in hate crimes. Hate crime is up and it is fueled by the kind of populist xenophobia you peddle,  she said.Needless to say, the British people were not happy about Trump s comments either.please don t mention us in your propaganda, we all hate you here.  TechnicallyRaarrrghh (@TechnicallyRon) October 20, 2017Once again, Trump made a fool of himself and demonstrated why America is a joke on the international stage.Featured Image: Drew Angerer/Getty Images
A quick look at the statistics shows that six of the 10 deadliest mass shootings on record in the US have occurred in the last decade, the top two less than 18 months apart, yet Republicans have generally been opposed to almost any form of gun control. However, that appears to be changing in the aftermath of yet another tragedy.Democrats, spearheaded by California Senator Dianne Feinstein, the ranking Democrat on the Judiciary Committee, have proposed a ban on an accessory known as a  bump stock,  which uses the recoil of a semi-automatic firearm to fire several hundred shots per minute without compromising on accuracy, something that really isn t necessary for even the most avid outdoorsman, and a device that few lawmakers had even heard of before Monday.The most surprising part of this proposal is that it is gaining support from Republicans across the board and it s the first time Republicans have even considered discussing any form of gun control since 2012, when 20-year-old Adam Lanza shot and killed 20 children aged between six and seven years old, as well as six adult staff members, at Sandy Hook Elementary School in Newtown, Connecticut.Republican support for the proposal, however, is a small victory along the long and bumpy road to becoming legislation. Not only will the measure need to be approved by Republicans on Capitol Hill, it will also need the backing of President Trump, whose campaign last year was heavily endorsed by the infinitely powerful National Rifle Association (NRA).All the same, it is an excellent start when a Congressman from Texas is the first Republican to support the ban on bump stocks. That Congressman is Bill Flores. I think they should be banned. There s no reason for a typical gun owner to own anything that converts a semi-automatic to something that behaves like an automatic,  Flores, a gun owner, said in an interview just off the House floor. Based on the videos I heard and saw, and now that I ve studied up on what a bump stock is   I didn t know there was such a thing   there s no reason for it,  he added. I have no problem from banning myself from owning it. Other House Republican moderates that agree with Flores include Charlie Dent and Ryan Costello from Pennsylvania, Leonard Lance of New Jersey and Pete King from New York. I m ready to say that they should not be in public use. I think they are a problem. I support a ban on bump stocks. I don t see any purpose for them,  Dent said. The law is clear to me that automatic weapons are banned in this country, as they should be. Featured image via Chip Somodevilla/Getty Images
Caleb Keeter, a lifelong proponent of the Second Amendment, and guitarist for Texas country outfit the Josh Abbott Band has had a strong change of heart regarding gun control. What changed his stance was  the events of last night  in which a gunman opened fire killing 58 people and injuring 515 others, marking it as the deadliest mass shooting in U.S. history. While  thoughts and prayers  are offered by the masses after each deadly shooting, Keeter took it a step further, posting a lengthy message on Twitter to express his personal thoughts after the attack.Keeter, who survived the attack, wrote,  I ve been a proponent of the 2nd amendment my entire life. Until the events of last night.   I cannot express how wrong I was. We actually have members of our crew with [Concealed Handgun Licenses], and legal firearms on the bus,  Keeter continued.  They were useless. We couldn t touch them for fear police might think we were part of the massacre and shoot us. A small group (or one man) laid waste to a city with dedicated, fearless police officers desperately trying to help, because of access to an insane amount of fire power.Enough is enough.Writing my parents and the love of my life a goodbye last night and a living will because I felt like I wasn t going to live through the night was enough for me to realize that this is completely and totally out of hand. These rounds were just powerful enough that my crew guys just standing in close proximity of a victim shot by this f ing coward received shrapnel wounds.We need gun control RIGHT. NOW. My biggest regret is that I stubbornly didn t realize it until my brothers on the road and myself were threatened by it. We are unbelievably fortunate to not be among the number of victims killed or seriously wounded by this maniac.pic.twitter.com/0NFjHf3PW2  Caleb Keeter (@Calebkeeter) October 2, 2017Some Twitter users wondered about his change of heart. Why now instead of when a gunman opened fire in 2012, slaughtering twenty first-graders and six adults at the Sandy Hook elementary school.On Twitter user wrote,  It s frustrating that some don t call the fire dept until the blaze is at their own front door. But we need more ppl on our side. Welcome. Caleb admitted that he s done nothing about gun violence which has rocked our country for years, but said he would like to do something now. You are all absolutely correct,  he tweeted.  I saw this happening for years and did nothing. But I d like to do what I can now. You are all absolutely correct. I saw this happening for years and did nothing. But I'd like to do what I can now. https://t.co/5mYA7D90X3  Caleb Keeter (@Calebkeeter) October 2, 2017In another tweet, he wrote,  That being said, I ll not live in fear of anyone. We will regroup, we ll come back, and we ll rock your fu*king faces off. Bet on it. It s OK to be for the Second Amendment and for gun control.  Keeter has a set of brass balls to come out publicly like that in support of gun control as the country music industry has close ties with the National Rifle Association.Image via YouTube screen capture.
Megyn Kelly may have departed Fox News for more legitimate pastures at NBC, but she s no less of a right-wing hack. If anything, she s openly doing Donald Trump s bidding from her new anchor chair. Case in point   Kelly decided to bring fringe conspiracy nut Alex Jones in for an interview. This is the same guy who says the mass shooting of more than 20 innocent small children and teachers at Sandy Hook Elementary School in Newtown Connecticut is a government hoax that used child actors to fool the world in order to promote gun control.Well, the mother of one of the victims of that very same shooting took Kelly to the woodshed for legitimizing Jones. Nelba Marquez-Greene took to Twitter and ripped Kelly apart:Hey @megynkelly , let me know if you want to give his victims equal air time. Promoting this fool is bad news. Do not encourage his abuse. https://t.co/WTJjFuSSuG  Nelba M rquez-Greene (@Nelba_MG) June 12, 2017To give a man like this such a platform normalizes behavior that isn't normal. How do I explain this to my son? https://t.co/lEVlBR8LI6  Nelba M rquez-Greene (@Nelba_MG) June 12, 2017Here you go @megynkelly   her name is Ana Grace M rquez-Greene. Say her name- stare at this & tell me it's worth it. @nbc #SandyHook pic.twitter.com/mKrU63KWmA  Nelba M rquez-Greene (@Nelba_MG) June 12, 2017In @megynkelly 's America, cruelty gets u on national TV on Father's Day. #SandyHook grieving dads will go to the cemetery. #thisisnotnormal  Nelba M rquez-Greene (@Nelba_MG) June 12, 2017Chelsea Clinton then chimed in to comfort the grieving mother:I am so sorry Nelba you continually confront disbelief and derision. It should be obvious how very, very wrong that is.  Chelsea Clinton (@ChelseaClinton) June 12, 2017There is no justification for amplifying lies (or a liar), particularly about unimaginable tragedy. I hope no parent, no person watches this https://t.co/nSt1MGGM2U  Chelsea Clinton (@ChelseaClinton) June 12, 2017After that, Shannon Watts, who founded Moms for Gun Sense in America, took her turn to school Kelly:This is the mother of a child murdered at Sandy Hook   a tragedy Alex Jones says never happened. How could you @megynkelly? #shameonNBC https://t.co/gHaHEhxGCU  Shannon Watts (@shannonrwatts) June 12, 2017Why isn't @megynkelly interviewing Sandy Hook families instead of lying, cruel man who has caused them added suffering? #shameonNBC @nbc https://t.co/yBo6NljTkP  Shannon Watts (@shannonrwatts) June 12, 2017Shame on @MegynKelly and #shameonNBC for allowing this cruel and overexposed liar question whether Sandy Hook happened. @nbc https://t.co/yBo6NlBucn  Shannon Watts (@shannonrwatts) June 12, 2017This is repulsive and immoral. How dare you highlight this "person" who accused Aurora and Sandy Hook parents of faking children's deaths?  Shannon Watts (@shannonrwatts) June 12, 2017Once Kelly saw the firestorm coming her way, she insisted that what she is doing is good journalism, since the orange goon in the Oval Office pretending to be president likes Alex Jones and appeared on his show:POTUS's been on & praises @RealAlexJones' show. He's giving Infowars a WH press credential. Many don't know him; our job is 2 shine a light. https://t.co/5e88BJyqnz  Megyn Kelly (@megynkelly) June 12, 2017No, Ms. Kelly. This is not shining a light. Just because the moron in the White House traffics in conspiracies and gets his  news  from lunatics doesn t mean that legitimate journalists need to give this kind of thing a platform. That s the whole point   THIS. IS. NOT. NORMAL.You are giving this bigoted fringe conspiracy theorist a huge platform from a legitimate news network, all the while causing more pain to the families of those murdered children. You should be ashamed of yourself. You and NBC owe these families an apology.As for NBC   if they want to retain their status as one of the main legitimate news networks, they ll fire this hack immediately and refuse to air her garbage.Featured image via Jemal Countess/Getty Images